---
- hosts: test-server
  become: true
  tasks:
    - name: update apt
      command: sudo apt-get update

    - name: install docker
      command: sudo apt install -y docker.io

    - name: start docker service
      command: sudo systemctl start docker

    - name: deploy registration application
      command: sudo docker run -itd -p 8081:80 nawaaz46/php:1.0
